### PR TITLE
deployment stuff

### PR DESCRIPTION
**Pull request by mwilkins74**
Just commenting-out unused code that was flagged during deployment.

### CODE REVIEW

**Comment by mwilkins74** [comment]
Deploy preview ready!
Screen Shot 2024-01-30 at 3 39 43 PM

Have not Published the site yet. Want to verify site name before I publish - `[kurt-sensenbrenner.netlify.app](https://kurt-sensenbrenner.netlify.app/)`

**Comment by mwilkins74** [comment]
Does bring up the question - Favicon?
It's (obviously) still the React Icon.

**Comment by ChuckBTaylor** [comment]
> Does bring up the question - Favicon? It's (obviously) still the React Icon.

Good question for the designer :) I'll ask

**Comment by ChuckBTaylor** [comment]
> Deploy preview ready! Screen Shot 2024-01-30 at 3 39 43 PM
> 
> Have not Published the site yet. Want to verify site name before I publish - `https://kurt-sensenbrenner.netlify.app/`

The domain doesn't really matter (yet), right? He owns a domain. Once the sight is ready, we'll point his domain at this site.

**Comment by ChuckBTaylor** [comment]
Super cool!

**Comment by mwilkins74** [comment]
Super cool and super easy!
There was some figuring to do but really smooth deployment.

**Review by kmdunn5 — APPROVED** [review]

**Pull request merged**
