### PR TITLE
`onClose` functionality to close NavList

### PR DESCRIPTION
**Pull request by mwilkins74**

### CODE REVIEW

**Comment by ChuckBTaylor** [comment]
Looks good. Just a conflict issue.

**Comment by mwilkins74** [comment]
Errors/conflicts fixed.

**Comment by ChuckBTaylor** [comment]
I think this PR is going to run into conflict with [Current Location Bottom Border](https://github.com/mwkwsd/sensensomething/pull/126)

**Comment by ChuckBTaylor** [comment]
That being said, changes look good.

**Review by ChuckBTaylor — APPROVED** [review]

**Comment by ChuckBTaylor** [comment]
Addresses #123

**Pull request merged**
