### PR TITLE
Modal Background

### PR DESCRIPTION
**Pull request by mwilkins74**
Is this what we're looking for?

Screen Shot 2024-04-03 at 3 28 38 PM

### CODE REVIEW

**Comment by ChuckBTaylor** [comment]
Looks close.  What about the "X" in the top right? 

What does it look like horizontally?

**Comment by mwilkins74** [comment]
See PR #111

**Comment by ChuckBTaylor** [comment]
What does it look like horizontal?

**Comment by mwilkins74** [comment]
By horizontal do you mean full screen?

Screen Shot 2024-04-11 at 1 41 06 PM

**Pull request closed without merging**
